### ISSUE TITLE
python 3.6 support?

### ISSUE THREAD

**Issue by boutros** [oslokommune/origo-cli#29]
Hei!

Det er veldig knotete å få installert dependencies på ubuntu 18.04 LTS, siden default python3 er versjon 3.6.
Er det mulig å støtte denne versjonen? Eventuelt lage en installasjonsoppsrift på hvordan man setter opp riktige dependencies på ubuntu?

**Comment by haavardeide** [comment]
@boutros - skal få laga oppskrift for installasjon via source, så via apt

**Comment by boutros** [comment]
Supert! :+1:

**Comment by boutros** [comment]
:+1: takker!
